version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "17:30"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  assignees:
  - dev01d
  ignore:
  - dependency-name: parcel-bundler
    versions:
    - "> 1.12.3, < 1.13"
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
